spring.application.name=NauGram
spring.application.version=1.0.4
server.servlet.session.timeout=60m

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
mail.password =
mail.user =


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.messages.basename=messages
spring.messages.encoding=UTF-8

naugram.media.root=E:/NauGramMedia
naugram.media.url-prefix=/media
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=250MB