spring.application.name=NauGram
spring.application.version=1.0.1
server.servlet.session.timeout=60m

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
mail.password =
mail.user =

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

