spring.application.name=NauGram
spring.application.version=1.0.4
server.servlet.session.timeout=60m

spring.datasource.url=jdbc:postgresql://localhost:5432/NauGram
spring.datasource.username=postgres
spring.datasource.password=root
mail.password =vrcx jgtj carm ltge
mail.user = naugram.support@gmail.com


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.messages.basename=messages
spring.messages.encoding=UTF-8